import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import { Outfit } from 'next/font/google';

const outfit_font = Outfit({
  weight: '400',
  variable: '--font-outfit',
});

const euorope_font = localFont({
  src: [
    {
      path: './Fonts/EuropaGrotesk.ttf',
      style: "normal",
      weight: "400",
    }
  ],
  variable: '--font-euorope',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${euorope_font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
